stages:
- publish


nightly:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:dev" --destination "${CI_REGISTRY_IMAGE}:latest"
    --build-arg VERSION=${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

stable:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - export TAG_MAJOR=$(echo $CI_COMMIT_TAG | cut -d. -f1)
  - export TAG_MINOR=$(echo $CI_COMMIT_TAG | cut -d. -f2)
  - export TAG_PATCH=$(echo $CI_COMMIT_TAG | cut -d. -f3)
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}.${TAG_MINOR}"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}.${TAG_MINOR}.${TAG_PATCH}"
    --build-arg VERSION=${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG

